[2025-10-02 02:01:41] INFO root: init_logging: logfile=logs\log_20251002_000141.txt
[2025-10-02 02:01:41] INFO __main__: Logging initialized
[2025-10-02 02:01:44] INFO root: Config loaded from config\gui_config.json
[2025-10-02 02:01:44] ERROR __main__: DB writer failed to start
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 630, in _db_writer_loop
    conn = sqlite3.connect(str(db_path), check_same_thread=True, timeout=5.0)
NameError: name 'sqlite3' is not defined
[2025-10-02 02:01:44] ERROR root: DB writer failed to start:
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 630, in _db_writer_loop
    conn = sqlite3.connect(str(db_path), check_same_thread=True, timeout=5.0)
NameError: name 'sqlite3' is not defined

