[2025-10-01 17:57:32] INFO root: init_logging: logfile=logs\log_20251001_155732.txt
[2025-10-01 17:57:32] INFO __main__: Logging initialized
[2025-10-01 17:57:35] CRITICAL root: Uncaught exception
Traceback (most recent call last):
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2807, in <module>
    main()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 2802, in main
    app = TradingAppExtended(root)
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 413, in __init__
    self._build_ui()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 1061, in _build_ui
    self._extend_status_tab_ui()
  File "C:\Users\soyko\Documents\git2\Market\project assistant\env.model_0.9\0.9f\fibopkg5\trading_gui_extended.py", line 987, in _extend_status_tab_ui
    frm_ws_ctrl = Frame(parent_tab)
NameError: name 'parent_tab' is not defined
